language: rust
rust:
  - nightly

env:
  global:
  - SCHANI_TEST=schani

matrix:
  include:
  - rust: nightly
    env: SCHANI_TEST=schani_import
  - rust: nightly
    env: SCHANI_TEST=schani_processor
  - rust: nightly
    env: SCHANI_TEST=schani_store
  fast_finish: true

branches:
  only:
  - master

cache: cargo

before_script:
  - cd $SCHANI_TEST

script:
  - echo Testing $SCHANI_TEST

  - cargo build --verbose
  - cargo test --verbose