language: rust
rust:
  - nightly

env:
  global:
  - SCHANI_TEST=schani

matrix:
  include:
  - rust: nightly
    env: SCHANI_TEST=schani_import
  - rust: nightly
    env: SCHANI_TEST=schani_processor
  - rust: nightly
    env: SCHANI_TEST=schani_store
  fast_finish: true

branches:
  only:
  - master

services:
  - mysql

cache: cargo

before_script:
  - cd $SCHANI_TEST
  - cargo install diesel_cli

script:
  - echo Testing $SCHANI_TEST

  # Build
  - cargo build --verbose

  # Migrate
  - if [[ "$SCHANI_TEST" = "schani_import" ]]; then diesel migration run; fi
  - if [[ "$SCHANI_TEST" = "schani_import" ]]; then diesel migration redo; fi

  # Test
  - cargo test --verbose